In [1]:
import numpy as np

In [2]:
arr = np.array([-1,0,1])
def softmax(arr):
    exps = np.exp(arr)
    return exps / np.sum(exps)
softmax(arr)

array([0.09003057, 0.24472847, 0.66524096])

In [4]:
def nll(a, y):
    pass
-np.log(.2)

1.6094379124341003

In [5]:
w = np.array([[1, -1, -2], [-1, 2, 1]])
x = np.array([[1, 1]]).T
y = np.array([[0, 1, 0]]).T

In [11]:
z = np.dot(w.T, x)
a = softmax(z)
wgrad = np.round(np.dot(x,(a - y).T), 3)
wgrad

array([[ 0.245, -0.335,  0.09 ],
       [ 0.245, -0.335,  0.09 ]])

In [15]:
w_new = w - 0.5 * wgrad
z = np.dot(w_new.T, x)
a = softmax(z)
a

array([[0.15912132],
       [0.77252695],
       [0.06835173]])

In [18]:
def dReLU_dz(z):
    return (z > 0) * 1.0

In [19]:
softmax(np.array([15,-13]))

array([1.00000000e+00, 6.91440011e-13])

In [22]:
X = np.array([[0.5,0,-3],[-.5,2,0.5]])
W = np.array([[1,0],[0,1],[-1,0],[0,-1]])
W0 = np.array([[-1],[-1],[-1],[-1]])

In [27]:
def ReLu(z):
    return np.maximum(z, 0)
ReLu(np.dot(W, X) + W0)

array([[0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 2.],
       [0., 0., 0.]])